apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-poinpik
  namespace: null
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poinpik-apps     # Menggunakan label aplikasi poinpik
  template:
    metadata:
      labels:
        app: poinpik-apps   # Label ini harus cocok dengan selector di atas dan di Service
    spec:
      containers:
      - name: nodejs-container
        image: canda22/poinpik-apps:main-30
        ports:
        - containerPort: 3000   # Node.js app tetap mendengarkan port 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-poinpik     # Nama Service diubah sesuai permintaanmu
  namespace: null
spec:
  type: NodePort
  selector:
    app: poinpik-apps       # Menghubungkan Service ini langsung ke Pod Deployment di atas
  ports:
    - protocol: TCP
      port: 80              # Port akses internal klaster (ClusterIP)
      targetPort: 3000      # Meneruskan trafik ke containerPort 3000 milik Node.js
      nodePort: 32324 
